apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-big-data-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: my-big-data-app
  # resourcePolicy:
  #   containerPolicies:
  #     - containerName: big-data-server
  #       controlledResources:
  #         - cpu
  #         - memory
  #       maxAllowed:
  #         cpu: 1
  #         memory: 800Mi
  #       minAllowed:
  #         cpu: 100m
  #         memory: 50Mi
  updatePolicy:
    updateMode: "Off"
...