---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-big-data-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-big-data-app
  template:
    metadata:
      labels:
        app: my-big-data-app
    spec:
      containers:
        - name: big-data-server
          image: dipugodocker/vmware-sol:latest
          imagePullPolicy: Always
          resources:
            # requests:
              # memory: "50Mi"
              # cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1"
          ports:
            - name: for-web
              containerPort: 8080
...