apiVersion: v1
kind: Pod
metadata:
  name: sql-server
  labels:
    app: database

spec:
  containers:
    - name: dba-server
      image: mysql:latest
      cmd: ['echo','Hello']
      ports:
        - containerPort: 80
...
